import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'EIC club',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (


   
      <div lang="en">


        <body className={inter.className}>{children}</body>
<div>
<hr  />
<span className='text-sm '  >&copy; 
Created by Abdullrahman Alajlan 
</span>
        

</div>
       
      </div>



  )
}
